#ifndef EMBEDDED_RESOURCES_H
#define EMBEDDED_RESOURCES_H

#include <FL/Fl_RGB_Image.H>

enum EmbeddedResourceType {
    EMBEDDED_RESOURCE_BINARY = 0,
    EMBEDDED_RESOURCE_PNG = 1
};

struct EmbeddedResourceEntry {
    const char* name;
    unsigned long offset;
    unsigned long size;
    EmbeddedResourceType type;
};

/* Definitions are generated by ResPacker into EmbeddedResourcesData.cpp. */
extern const unsigned char gEmbeddedResourceData[];
extern const unsigned long gEmbeddedResourceDataSize;
extern const EmbeddedResourceEntry gEmbeddedResources[];
extern const unsigned int gEmbeddedResourceCount;

class EmbeddedResources {
public:
    static const EmbeddedResourceEntry* find(const char* name);

    static const unsigned char* getData(const char* name,
                                        unsigned long* size,
                                        EmbeddedResourceType* type);

    static bool copyData(const char* name,
                         void* destination,
                         unsigned long expectedSize);

    /*
     * PNG remains compressed in the executable. It is decoded directly from
     * gEmbeddedResourceData by libpng; no temporary file is created.
     * The returned Fl_RGB_Image owns its decoded pixel buffer.
     */
    static Fl_RGB_Image* loadPng(const char* name);
};

#endif
